apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employee-app
  template:
    metadata:
      labels:
        app: employee-app
    spec:
      containers:
        - name: employee-app
          image: gmaldo/employee_app:1.0.1
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: "mongodb://mongo-0.mongo-headless-service:27017,mongo-1.mongo-headless-service:27017,mongo-2.mongo-headless-service:27017/employee_db?replicaSet=rs0"
            - name: PORT
              value: "3000"
